simplifyEvents <- function (df) {
# This function consolidates many storm data types together by
# repeated calls to mergeEvents().  The purpose of this function is to
# ensure that only one reporting type is used for multiple text
# descriptions.  For example, three of the top events are TSTM WIND,
# THUNDERSTORM WIND, THUNDERSTORM WINDS, even though they refer to the
# same type of event.  This function repeatedly calls mergeEvents() to
# reduce the number of distinct event types.
#
# Input:  A data frame of storm data.
# Output: The same data frame, but with many event types rewritten.
    
    # Typos with leading spaces
    df <- mergeEvents(df, "HIGH SURF ADVISORY",  "   HIGH SURF ADVISORY")
    df <- mergeEvents(df, "COASTAL FLOOD" , " COASTAL FLOOD"  )
    df <- mergeEvents(df, "FLASH FLOOD", " FLASH FLOOD" )
    df <- mergeEvents(df, "LIGHTNING"   , " LIGHTNING"   )
    df <- mergeEvents(df, "TSTM WIND", " TSTM WIND")
    df <- mergeEvents(df, "TSTM WIND", " TSTM WIND (G45)")
    df <- mergeEvents(df, "WATERSPOUT", " WATERSPOUT")
    df <- mergeEvents(df, "WIND", " WIND")
    
    df <- mergeEvents(df, "AVALANCHE" , "AVALANCE"  )
    df <- mergeEvents(df, "BEACH EROSION", "BEACH EROSIN" )
    df <- mergeEvents(df, "WIND CHILL", "BITTER WIND CHILL" )

    df <- mergeEvents(df, "BLIZZARD", 
                      "BLIZZARD AND EXTREME WIND CHIL",
                      "BLIZZARD SUMMARY",
                      "BLIZZARD WEATHER",
                      "BLIZZARD/FREEZING RAIN",
                      "BLIZZARD/HEAVY SNOW",
                      "BLIZZARD AND HEAVY SNOW",
                      "BLIZZARD/HIGH WIND",
                      "BLIZZARD/WINTER STORM"
                       )

    df <- mergeEvents(df, "BLOW-OUT TIDE", "BLOW-OUT TIDES")

    df <- mergeEvents(df, "BLOWING SNOW",
                      "BLOWING SNOW & EXTREME WIND CH",
                      "BLOWING SNOW- EXTREME WIND CHI",
                      "BLOWING SNOW/EXTREME WIND CHIL"
                      )
    
    df <- mergeEvents(df,"BRUSH FIRE" , "BRUSH FIRES")

    df <- mergeEvents(df, "COASTAL FLOOD",
                      "COASTAL FLOODING",
                      "COASTALFLOOD",
                      "COASTAL  FLOODING/EROSION",
                      "CSTL FLOODING/EROSION"
                      )

    df <- mergeEvents(df, "COLD",
                      "COLD TEMPERATURES",
                      "COLD AND FROST",
                      "COLD AND SNOW",
                      "COLD TEMPERATURE",
                      "COLD WEATHER",
                      "COLD/WIND CHILL",
                      "COLD/WINDS",
                      "RECORD  COLD",
                      "RECORD COLD",                   
                      "RECORD COLD AND HIGH WIND",
                      "RECORD COLD/FROST",
                      "RECORD COOL",
                      "UNSEASONABLE COLD",
                      "UNSEASONABLY COLD",
                      "UNSEASONABLY COOL",
                      "UNSEASONABLY COOL & WET",                         
                      "UNSEASONAL LOW TEMP",
                      "UNUSUALLY COLD", 
                      "PROLONG COLD",                  
                      "PROLONG COLD/SNOW",                              
                      "LOW TEMPERATURE RECORD",
                      "LOW TEMPERATURE",               
                      "EXTREME COLD",                  
                      "EXTREME COLD/WIND CHILL",
                      "EXTENDED COLD"
                      )

    df <- mergeEvents(df, "DRY MICROBURST",
                      "DRY MICROBURST 50",
                      "DRY MICROBURST 53",
                      "DRY MICROBURST 58",
                      "DRY MICROBURST 61",
                      "DRY MICROBURST 84",
                      "DRY MICROBURST WINDS",
                      "DRY MIRCOBURST WINDS"
                      )

    df <- mergeEvents(df, "DROUGHT",
                      "VERY DRY",
                      "UNSEASONABLY DRY",
                      "DRIEST MONTH",  
                      "DROUGHT", 
                      "DROUGHT/EXCESSIVE HEAT", 
                      "DRY",  
                      "DRY HOT WEATHER",
                      "DRY SPELL",                     
                      "DRY WEATHER",
                      "DRYNESS",  
                      "EXCESSIVELY DRY" 
                      )

    df <- mergeEvents(df, "FLASH FLOOD",
                      "FLASH FLOOD",
                      "FLASH FLOOD - HEAVY RAIN",
                      "FLASH FLOOD FROM ICE JAMS",
                      "FLASH FLOOD LANDSLIDES",
                      "FLASH FLOOD WINDS",
                      "FLASH FLOOD/",
                      "FLASH FLOOD/ FLOOD",
                      "FLASH FLOOD/ STREET",
                      "FLASH FLOOD/FLOOD",
                      "FLASH FLOOD/HEAVY RAIN",
                      "FLASH FLOOD/LANDSLIDE",
                      "FLASH FLOODING",
                      "FLASH FLOODING/FLOOD",
                      "FLASH FLOODING/THUNDERSTORM WI",
                      "FLASH FLOODS",
                      "FLASH FLOOODING"
                      )

    df <- mergeEvents(df, "FLOOD",
                      "FLOOD & HEAVY RAIN",
                      "FLOOD FLASH",                   
                      "FLOOD FLOOD/FLASH",
                      "FLOOD WATCH/",                  
                      "FLOOD/FLASH",
                      "FLOOD/FLASH FLOOD",
                      "FLOOD/FLASH FLOODING",
                      "FLOOD/FLASH/FLOOD",
                      "FLOOD/FLASHFLOOD",
                      "FLOOD/RAIN/WIND",
                      "FLOOD/RAIN/WINDS",
                      "FLOOD/RIVER FLOOD",
                      "FLOOD/STRONG WIND",
                      "FLOODING",
                      "FLOODING/HEAVY RAIN",
                      "FLOODS",
                      "RIVER AND STREAM FLOOD",
                      "RIVER FLOOD",
                      "RIVER FLOODING",
                      "RURAL FLOOD",
                      "STREAM FLOODING",
                      "STREET FLOOD",
                      "STREET FLOODING",
                      "URBAN AND SMALL STREAM FLOOD",
                      "URBAN AND SMALL STREAM FLOODIN",
                      "URBAN FLOOD",
                      "URBAN FLOOD LANDSLIDE",
                      "URBAN FLOODING",
                      "URBAN FLOODS",
                      "URBAN SMALL STREAM FLOOD",
                      "URBAN/SMALL FLOODING",
                      "URBAN/SMALL STREAM  FLOOD",
                      "URBAN/SMALL STREAM FLOODING",
                      "URBAN/SMALL STRM FLDG",
                      "URBAN/SML STREAM FLD",
                      "URBAN/SML STREAM FLDG",         
                      "URBAN/STREET FLOODING",
                      "TIDAL FLOOD",
                      "TIDAL FLOODING",
                      "SMALL STREAM AND URBAN FLOOD",
                      "SMALL STREAM AND URBAN FLOODIN",
                      "SMALL STREAM FLOOD",
                      "SMALL STREAM FLOODING",
                      "SMALL STREAM URBAN FLOOD",
                      "SMALL STREAM/URBAN FLOOD",
                      "SML STREAM FLD",
                      "SNOWMELT FLOODING",
                      "MAJOR FLOOD",
                      "LOCAL FLASH FLOOD",
                      "LOCAL FLOOD"
                      )

    df <- mergeEvents(df, "HAIL",
                      "HAIL 0.75",
                      "HAIL 0.88",
                      "HAIL 075",
                      "HAIL 088",
                      "HAIL 1.00",
                      "HAIL 1.75",
                      "HAIL 1.75)",
                      "HAIL 100",
                      "HAIL 125",
                      "HAIL 150",
                      "HAIL 175",
                      "HAIL 200",
                      "HAIL 225",
                      "HAIL 275",
                      "HAIL 450",
                      "HAIL 75",
                      "HAIL 80",
                      "HAIL 88",
                      "HAIL ALOFT",
                      "HAIL DAMAGE",
                      "HAIL FLOODING",
                      "HAIL STORM",
                      "HAIL(0.75)",
                      "HAIL/ICY ROADS",
                      "HAIL/WIND",
                      "HAIL/WINDS",
                      "HAILSTORM",
                      "HAILSTORMS",
                      "SMALL HAIL"
                      )

    df <- mergeEvents(df, "HEAT",
                      "HEAT DROUGHT",
                      "HEAT WAVE",
                      "HEAT WAVE DROUGHT",
                      "HEAT WAVES",
                      "HEAT/DROUGHT",
                      "HEATBURST",
                      "UNSEASONABLY HOT",
                      "UNSEASONABLY WARM",
                      "UNSEASONABLY WARM & WET",
                      "UNSEASONABLY WARM AND DRY",
                      "UNSEASONABLY WARM YEAR",
                      "UNSEASONABLY WARM/WET",
                      "UNUSUAL WARMTH",
                      "UNUSUALLY WARM",
                      "UNUSUAL/RECORD WARMTH",
                      "VERY WARM",
                      "WARM WEATHER",
                      "RECORD WARM",
                      "RECORD WARM TEMPS.",
                      "RECORD WARMTH",
                      "RECORD HEAT",
                      "RECORD HEAT WAVE",
                      "RECORD HIGH",
                      "RECORD HIGH TEMPERATURE",
                      "RECORD HIGH TEMPERATURES",
                      "PROLONG WARMTH",
                      "EXCESSIVE HEAT",
                      "EXCESSIVE HEAT/DROUGHT"
                      )

    # Hurricanes, typhoons, and cyclones are all the same!
    # http://oceanservice.noaa.gov/facts/cyclone.html
    df <- mergeEvents(df, "HURRICANE",
                      "HURRICANE/TYPHOON",
                      "HURRICANE EDOUARD",
                      "HURRICANE EMILY",
                      "HURRICANE ERIN",
                      "HURRICANE FELIX",
                      "HURRICANE GORDON",
                      "HURRICANE OPAL",                
                      "HURRICANE OPAL/HIGH WINDS",
                      "HURRICANE-GENERATED SWELLS"    
                      )

    df <- mergeEvents(df, "THUNDERSTORM WIND",
                      "SEVERE THUNDERSTORM WINDS",
                      "THUDERSTORM WINDS",
                      "THUNDEERSTORM WINDS",
                      "THUNDERESTORM WINDS",
                      "THUNDERSTORM  WINDS",
                      "THUNDERSTORM W INDS",
                      "THUNDERSTORM WIND",
                      "THUNDERSTORM WIND",
                      "THUNDERSTORM WIND (G40)",
                      "THUNDERSTORM WIND 50",
                      "THUNDERSTORM WIND 52",
                      "THUNDERSTORM WIND 56",
                      "THUNDERSTORM WIND 59",
                      "THUNDERSTORM WIND 59 MPH",
                      "THUNDERSTORM WIND 59 MPH.",
                      "THUNDERSTORM WIND 60 MPH",
                      "THUNDERSTORM WIND 65 MPH",
                      "THUNDERSTORM WIND 65MPH",
                      "THUNDERSTORM WIND 69",
                      "THUNDERSTORM WIND 98 MPH",
                      "THUNDERSTORM WIND G50",
                      "THUNDERSTORM WIND G51",
                      "THUNDERSTORM WIND G52",
                      "THUNDERSTORM WIND G55",
                      "THUNDERSTORM WIND G60",
                      "THUNDERSTORM WIND G61",
                      "THUNDERSTORM WIND TREES",
                      "THUNDERSTORM WIND.",
                      "THUNDERSTORM WIND/ TREE",
                      "THUNDERSTORM WIND/ TREES",
                      "THUNDERSTORM WIND/AWNING",
                      "THUNDERSTORM WIND/HAIL",
                      "THUNDERSTORM WIND/LIGHTNING",
                      "THUNDERSTORM WINDS",
                      "THUNDERSTORM WINDS      LE CEN",
                      "THUNDERSTORM WINDS 13",
                      "THUNDERSTORM WINDS 2",
                      "THUNDERSTORM WINDS 50",
                      "THUNDERSTORM WINDS 52",
                      "THUNDERSTORM WINDS 53",
                      "THUNDERSTORM WINDS 60",
                      "THUNDERSTORM WINDS 61",
                      "THUNDERSTORM WINDS 62",
                      "THUNDERSTORM WINDS 63 MPH",
                      "THUNDERSTORM WINDS AND",
                      "THUNDERSTORM WINDS FUNNEL CLOU",
                      "THUNDERSTORM WINDS G",
                      "THUNDERSTORM WINDS G60",
                      "THUNDERSTORM WINDS HAIL",
                      "THUNDERSTORM WINDS HEAVY RAIN",
                      "THUNDERSTORM WINDS LIGHTNING",
                      "THUNDERSTORM WINDS SMALL STREA",
                      "THUNDERSTORM WINDS URBAN FLOOD",
                      "THUNDERSTORM WINDS.",
                      "THUNDERSTORM WINDS/ FLOOD",
                      "THUNDERSTORM WINDS/ HAIL",
                      "THUNDERSTORM WINDS/FLASH FLOOD",
                      "THUNDERSTORM WINDS/FLOODING",
                      "THUNDERSTORM WINDS/FUNNEL CLOU",
                      "THUNDERSTORM WINDS/HAIL",
                      "THUNDERSTORM WINDS/HEAVY RAIN",
                      "THUNDERSTORM WINDS53",
                      "THUNDERSTORM WINDSHAIL",
                      "THUNDERSTORM WINDSS",
                      "THUNDERSTORM WINS",
                      "THUNDERSTORMS WIND",
                      "THUNDERSTORMS WINDS",
                      "THUNDERSTORMW",
                      "THUNDERSTORMW 50",
                      "THUNDERSTORMW WINDS",
                      "THUNDERSTORMWINDS",
                      "THUNDERSTROM WIND",
                      "THUNDERSTROM WINDS",
                      "THUNDERTORM WINDS",
                      "THUNDERTSORM WIND",
                      "THUNDESTORM WINDS",
                      "THUNERSTORM WINDS",
                      "TSTM WIND",
                      "TSTM WIND  (G45)",
                      "TSTM WIND (41)",
                      "TSTM WIND (G35)",
                      "TSTM WIND (G40)",
                      "TSTM WIND (G45)",
                      "TSTM WIND 40",
                      "TSTM WIND 45",
                      "TSTM WIND 50",
                      "TSTM WIND 51",
                      "TSTM WIND 52",
                      "TSTM WIND 55",
                      "TSTM WIND 65)",
                      "TSTM WIND AND LIGHTNING",
                      "TSTM WIND DAMAGE",
                      "TSTM WIND G45",
                      "TSTM WIND G58",
                      "TSTM WIND/HAIL",
                      "TSTM WINDS",
                      "TSTM WND",
                      "TSTMW",
                      "TUNDERSTORM WIND"
                      )

    df <- mergeEvents(df, "THUNDERSTORM",
                      "TSTM",
                      "TSTM HEAVY RAIN",
                      "SEVERE THUNDERSTORM",
                      "SEVERE THUNDERSTORMS",
                      "THUNDERSNOW",
                      "THUNDERSNOW SHOWER",
                      "THUNDERSTORM DAMAGE",
                      "THUNDERSTORM DAMAGE TO",
                      "THUNDERSTORM HAIL",
                      "THUNDERSTORMS"
                      )

    df <- mergeEvents(df, "RAIN",
                      "HEAVY RAIN",
                      "HEAVY RAIN AND FLOOD",
                      "HEAVY RAIN AND WIND",
                      "HEAVY RAIN EFFECTS",
                      "HEAVY RAIN; URBAN FLOOD WINDS;",
                      "HEAVY RAIN/FLOODING",
                      "HEAVY RAIN/HIGH SURF",
                      "HEAVY RAIN/LIGHTNING",
                      "HEAVY RAIN/MUDSLIDES/FLOOD",
                      "HEAVY RAIN/SEVERE WEATHER",
                      "HEAVY RAIN/SMALL STREAM URBAN",
                      "HEAVY RAIN/SNOW",
                      "HEAVY RAIN/URBAN FLOOD",
                      "HEAVY RAIN/WIND",
                      "HEAVY RAINFALL",
                      "HEAVY RAINS",
                      "HEAVY RAINS/FLOODING",
                      "TORRENTIAL RAIN",
                      "TORRENTIAL RAINFALL",
                      "UNSEASONABLY WET",
                      "UNSEASONAL RAIN",
                      "RECORD/EXCESSIVE RAINFALL",
                      "MONTHLY RAINFALL"
                      )

    df <- mergeEvents(df, "ICE",
                      "ICE AND SNOW",
                      "ICE FLOES",
                      "ICE FOG",
                      "ICE JAM",
                      "ICE JAM FLOOD (MINOR",
                      "ICE JAM FLOODING",
                      "ICE ON ROAD",
                      "ICE PELLETS",
                      "ICE ROADS",
                      "ICE STORM",
                      "ICE STORM AND SNOW",
                      "ICE STORM/FLASH FLOOD",
                      "ICE/SNOW",
                      "ICE/STRONG WINDS"
                      )

    df <- mergeEvents(df, "SNOW",
                      "HEAVY SNOW",
                      "HEAVY SNOW   FREEZING RAIN",
                      "HEAVY SNOW & ICE",
                      "HEAVY SNOW AND",
                      "HEAVY SNOW AND HIGH WINDS",
                      "HEAVY SNOW AND ICE",
                      "HEAVY SNOW AND ICE STORM",
                      "HEAVY SNOW AND STRONG WINDS",
                      "HEAVY SNOW ANDBLOWING SNOW",
                      "HEAVY SNOW SHOWER",
                      "HEAVY SNOW SQUALLS",
                      "HEAVY SNOW-SQUALLS",
                      "HEAVY SNOW/BLIZZARD",
                      "HEAVY SNOW/BLIZZARD/AVALANCHE",
                      "HEAVY SNOW/BLOWING SNOW",
                      "HEAVY SNOW/FREEZING RAIN",
                      "HEAVY SNOW/HIGH",
                      "HEAVY SNOW/HIGH WIND",
                      "HEAVY SNOW/HIGH WINDS",
                      "HEAVY SNOW/HIGH WINDS & FLOOD",
                      "HEAVY SNOW/HIGH WINDS/FREEZING",
                      "HEAVY SNOW/ICE",
                      "HEAVY SNOW/ICE STORM",
                      "HEAVY SNOW/SLEET",
                      "HEAVY SNOW/SQUALLS",
                      "HEAVY SNOW/WIND",
                      "HEAVY SNOW/WINTER STORM",
                      "RECORD SNOW",
                      "RECORD SNOW/COLD",
                      "RECORD SNOWFALL",
                      "RECORD WINTER SNOW",
                      "SNOW ACCUMULATION",
                      "SNOW ADVISORY",
                      "SNOW AND COLD",
                      "SNOW AND HEAVY SNOW",
                      "SNOW AND ICE",
                      "SNOW AND ICE STORM",
                      "SNOW AND SLEET",
                      "SNOW AND WIND",
                      "SNOW DROUGHT",
                      "SNOW FREEZING RAIN",
                      "SNOW SHOWERS",
                      "SNOW SLEET",
                      "SNOW SQUALL",
                      "SNOW SQUALLS",
                      "SNOW- HIGH WIND- WIND CHILL",
                      "SNOW/ BITTER COLD",
                      "SNOW/ ICE",
                      "SNOW/BLOWING SNOW",
                      "SNOW/COLD",
                      "SNOW/FREEZING RAIN",
                      "SNOW/HEAVY SNOW",
                      "SNOW/HIGH WINDS",
                      "SNOW/ICE",
                      "SNOW/ICE STORM",
                      "SNOW/RAIN",
                      "SNOW/RAIN/SLEET",
                      "SNOW/SLEET",
                      "SNOW/SLEET/FREEZING RAIN",
                      "SNOW/SLEET/RAIN",
                      "SNOW\\COLD",
                      "SNOWFALL RECORD",
                      "SNOWSTORM",
                      "UNUSUALLY LATE SNOW",
                      "MONTHLY SNOWFALL"
                      )

    df <- mergeEvents(df, "TORNADO",
                      "TORNADO F0",
                      "TORNADO F1",
                      "TORNADO F2",
                      "TORNADO F3",
                      "TORNADOES",
                      "TORNADOS",
                      "TORNDAO"
                      )

    df <- mergeEvents(df, "WIND",
                      "HIGH WIND",
                      "HIGH WIND (G40)",
                      "HIGH WIND 48",
                      "HIGH WIND 63",
                      "HIGH WIND 70",
                      "HIGH WIND AND HEAVY SNOW",
                      "HIGH WIND AND HIGH TIDES",
                      "HIGH WIND AND SEAS",
                      "HIGH WIND DAMAGE",
                      "HIGH WIND/ BLIZZARD",
                      "HIGH WIND/BLIZZARD",
                      "HIGH WIND/BLIZZARD/FREEZING RA",
                      "HIGH WIND/HEAVY SNOW",
                      "HIGH WIND/LOW WIND CHILL",
                      "HIGH WIND/SEAS",
                      "HIGH WIND/WIND CHILL",
                      "HIGH WIND/WIND CHILL/BLIZZARD",
                      "HIGH WINDS",
                      "HIGH WINDS 55",
                      "HIGH WINDS 57",
                      "HIGH WINDS 58",
                      "HIGH WINDS 63",
                      "HIGH WINDS 66",
                      "HIGH WINDS 67",
                      "HIGH WINDS 73",
                      "HIGH WINDS 76",
                      "HIGH WINDS 80",
                      "HIGH WINDS 82",
                      "HIGH WINDS AND WIND CHILL",
                      "HIGH WINDS DUST STORM",
                      "HIGH WINDS HEAVY RAINS",
                      "HIGH WINDS/",
                      "HIGH WINDS/COASTAL FLOOD",
                      "HIGH WINDS/COLD",
                      "HIGH WINDS/FLOODING",
                      "HIGH WINDS/HEAVY RAIN",
                      "HIGH WINDS/SNOW",
                      "WIND",
                      "STRONG WIND",
                      "STRONG WIND GUST",
                      "STRONG WINDS",
                      "WIND",
                      "WIND",
                      "WIND DAMAGE",
                      "WIND GUSTS",
                      "WIND STORM",
                      "WIND/HAIL",
                      "WINDS",
                      "WND",
                      "WIND ADVISORY",
                      "STORM FORCE WINDS",
                      "NON TSTM WIND",
                      "NON-SEVERE WIND DAMAGE",
                      "NON-TSTM WIND"
                      )

    df <- mergeEvents(df, "WINTER",
                      "WINTER MIX",
                      "WINTER STORM",
                      "WINTER STORM HIGH WINDS",
                      "WINTER STORM/HIGH WIND",
                      "WINTER STORM/HIGH WINDS",
                      "WINTER STORMS",
                      "WINTER WEATHER",
                      "WINTER WEATHER MIX",
                      "WINTER WEATHER/MIX",
                      "WINTERY MIX",
                      "WINTRY MIX"
                      )

    df <- mergeEvents(df,"WILDFIRE","WILD/FOREST FIRE")

    # Return the modified data frame
    df
}
