---
title: "Economic and Human Consequences of Storms: An Analysis of NOAA Storm Data"
output: 
  html_document:
    keep_md: true
---

# Synopsis

Synopsis: Immediately after the title, there should be a synopsis
which describes and summarizes your analysis in at most 10 complete
sentences.

# Data Processing

There should be a section titled Data Processing which describes (in
words and code) how the data were loaded into R and processed for
analysis. In particular, your analysis must start from the raw CSV
file containing the data. You cannot do any preprocessing outside the
document. If preprocessing is time-consuming you may consider using
the cache = TRUE option for certain code chunks.

# Results

There should be a section titled Results in which your results are presented.

The analysis document must have at least one figure containing a plot.

Your analyis must have no more than three figures. Figures may have
multiple plots in them (i.e. panel plots), but there cannot be more
than three figures total.
